x-deploy-policy: &x-deploy-policy
  replicas: ${PROMETHEUS_REPLICAS:-2}
  placement:
    max_replicas_per_node: 1
    constraints:
      - node.role == manager
      - node.labels.prometheus == true
    preferences:
      - spread: node.labels.prometheus
  update_config:
    parallelism: 1
    delay: 30s
    order: stop-first
    failure_action: rollback
  rollback_config:
    parallelism: 1
    delay: 30s
  restart_policy:
    condition: on-failure
    delay: 30s
    max_attempts: 3
    window: 120s

x-default-logging: &x-default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

networks:
  dockerswarm_monitoring:
    name: dockerswarm_monitoring
    external: true

volumes:
  prometheus:
    external: true

configs:
  prometheus-config:
    template_driver: golang
    file: configs/prometheus.yml

  # Scrape configs
  scrape-configs-dockerswarm-nodes:
    file: configs/scrape_configs/dockerswarm-nodes.yml
  scrape-configs-dockerswarm-tasks:
    file: configs/scrape_configs/dockerswarm-tasks.yml
  scrape-configs-dockerswarm-cadvisor:
    file: configs/scrape_configs/dockerswarm-cadvisor.yml

  # Rules
  alerting-rules-node:
    file: configs/rules/node.yml
  alerting-rules-service:
    file: configs/rules/service.yml
  alerting-rules-task:
    file: configs/rules/task.yml

services:
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-latest}
    hostname: prometheus-{{.Task.Slot}}
    user: root
    command:
      - "--log.level=info"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.size=60GB"
      - "--storage.tsdb.retention.time=30d"
    networks:
      - dockerswarm_monitoring
    ports:
      - ${PROMETHEUS_PORT:-9090}:9090
    volumes:
      - prometheus:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro
    configs:
      - source: prometheus-config
        target: /etc/prometheus/prometheus.yml

      # Scrape configs
      - source: scrape-configs-dockerswarm-nodes
        target: /etc/prometheus/scrape_configs/dockerswarm-nodes.yml
      - source: scrape-configs-dockerswarm-tasks
        target: /etc/prometheus/scrape_configs/dockerswarm-tasks.yml
      - source: scrape-configs-dockerswarm-cadvisor
        target: /etc/prometheus/scrape_configs/dockerswarm-cadvisor.yml

      # Rules
      - source: alerting-rules-node
        target: /etc/prometheus/rules/node.yml
      - source: alerting-rules-service
        target: /etc/prometheus/rules/service.yml
      - source: alerting-rules-task
        target: /etc/prometheus/rules/task.yml
    deploy: *x-deploy-policy
    logging: *x-default-logging
