x-deploy-policy: &x-deploy-policy
  replicas: 2
  placement:
    max_replicas_per_node: 1
    constraints:
      - node.role == manager
    preferences:
      - spread: node.labels.prometheus
  update_config:
    parallelism: 1
    delay: 30s
    order: stop-first
    failure_action: rollback
  rollback_config:
    parallelism: 1
    delay: 30s
  restart_policy:
    condition: on-failure
    delay: 30s
    max_attempts: 3
    window: 120s

x-default-logging: &x-default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

configs:
  prometheus-config:
    name: prometheus-config-v1
    file: configs/prometheus.yml

  # Scrape configs
  scrape-configs-docker:
    name: prometheus-scrape-configs-docker-v1
    file: configs/scrape_configs/docker.yml
  scrape-configs-dockerswarm:
    name: prometheus-scrape-configs-dockerswarm-v1
    file: configs/scrape_configs/dockerswarm.yml

  # Rules
  alerting-rules-node:
    name: prometheus-alerting-rules-node-v1
    file: configs/rules/node.yml
  alerting-rules-service:
    name: prometheus-alerting-rules-service-v1
    file: configs/rules/service.yml
  alerting-rules-task:
    name: prometheus-alerting-rules-task-v1
    file: configs/rules/task.yml

services:
  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus-{{.Task.Slot}}-{{.Task.ID}}
    user: root
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.size=60GB"
      - "--storage.tsdb.retention.time=30d"
      - "--log.level=info"
    environment:
      - TASK_SLOT={{.Task.Slot}}
    networks:
      - dockerswarm_monitoring
    ports:
      - 9090:9090
    volumes:
      - prometheus:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro
    configs:
      - source: prometheus-config
        target: /etc/prometheus/prometheus.yml

      # Scrape configs
      - source: scrape-configs-docker
        target: /etc/prometheus/scrape_configs/docker.yml
      - source: scrape-configs-dockerswarm
        target: /etc/prometheus/scrape_configs/dockerswarm.yml

      # Rules
      - source: alerting-rules-node
        target: /etc/prometheus/rules/node.yml
      - source: alerting-rules-service
        target: /etc/prometheus/rules/service.yml
      - source: alerting-rules-task
        target: /etc/prometheus/rules/task.yml
    deploy: *x-deploy-policy
    logging: *x-default-logging

volumes:
  prometheus:
    name: prometheus-{{.Task.Slot}}

networks:
  dockerswarm_monitoring:
    name: dockerswarm_monitoring
    external: true
